dist: trusty
language: node_js
node_js:
- '8'
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
before_script:
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
before_deploy:
- tar -tf $(npm pack)
install:
- npm install
script:
- npm test
- npm run build
env:
  secure: mkyiKGXQ8wkx4kSi/x7kProXE76E2Ix5xP+xHAcTpMhsFJYsyFE8LR8wC7UWxg80nbww6P1mWpJkMPm2QnWW8OSuKh9pF2bluTU7VAf68JHROA55FZauO0NgLWxF1tog/RLaTXBzoqXBx5+Zlcp2jl4UdsDSIr/1TogSEC7hV3dMiqzTsiC09RnAgtGsUfzDjCGVgyz2yDBMCoi+kfzJiRz7f1dW5GxhUypuV4jjEXTt1V6XrIA0C/uD27LP+kswHadMT6HURPiWEJteKNFz6hnfXttF1XmTwW++kzahDoap607oLszz+g8ss/9F0ILyO3tffyKnoEOImJLogvLUm3slxfHvh9PYh7x8oyPHFtfs7QAJ5Q2Cr23VvwJNslkuNCphEsQJS/HQ70VuSF6MlGrhbsLGp8kEFZrXADqojkGQ/duPk3QykiXUaUxr0uPEllptOLh5TTKYarRM/IVv4kE5iC4egJXouKxwwL5LIglnyCTycEdTLv/IUfYap8ABqi20eBm+AJGk44Z72fl+G/xoPrzbtVosQfPbuLurVJHHDDExHM3bFqfUNnB9xIEwWTihSc6ycI7IhuMQlg1G1t5rRY5YyVQN/4oP4k6qNgYbJs9PrxfyMw7Z+dSg/L2SyJbc/ReNiFkvpTNDYGY/dULvx1uGM1NGdmC+z+nljfk=
deploy:
  provider: npm
  skip_cleanup: true
  email: webapps.ops@ni.com
  api_key:
    secure: uqKJHqC+2q1oLuKxhLy7kmZz+nVdp0lFyjFe/T4koxwIzBCJlHR7cdF0QbIPwj/PdQ+CUeWW6ZU9vkKhu44SA8jZPBeF1kMYKVS3i/LMggJgq/Dij9INVUk7BtT1vkPBxJ7vLG2LpYlBta81yHb6F9xF6j7JMhs4Y2rgYBTjvitgmkh8vfoj+LlaEcEPc4HHEPX8tyYo8F1DNj8xl+sATd8iO8w5sClnxvI0OchKZCfeMprwKQaRIYLTNgwqqdog24CT0SAvgVAz+egnPxcP/2jm8tYaomy0QeQenjkuuUw1mqkeXf7KbCF3722Ov5JyQFBxKpX/5OGiNr0sCOQxmY1+TJ5lujcGul2Rse7w//ijYmUpAMBDSrczH9DpmS9qIeVsMPIEp608YiFStzJ2+a0uMR6yofho6FxD9EsRwrraH6dhVg0olxrs3SiXsdkEmaFtfOQy0FXy54lBkRzdlEbTN4DED9/dGHMsx+RQ12YSO8moQ9xny2+1Iyvtam5cfqzAQLAdqOecbeZbwOcOzhYJQzpLCVOTpidYEYxPqJkXeo8pTlrOGBEETmymCz9+aZEyzRmAjSvq97Ba+BkAXLOAk4SL5MtsYlPpBzk55XYOJNPa/wEm0iAu+IisLrVGsqQImZNkBsbbjNQ5DvFWyKKHNU5JflZ5YdQK41oMvjU=
  on:
    tags: true
    repo: flot/flot-plugins
