dist: trusty
language: node_js
node_js:
- '8'
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
before_script:
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
before_deploy:
- tar -tf $(npm pack)
install:
- npm install
script:
- npm test
- npm run build
env:
  global:
    secure: b8N5ilujDZuoJrBMZS8HMgyLOUT12M/5GKMXxQFoZuxzcnijTJjJZAMkm4yXB7jEZQeWHcXscHcBKr/yFH/M4UMt7AHvzZVyZvYDGALgWC8Z0KwGjqZUTEbvs22UXo+hHu/PS0BIXHphohGKnRpImCUltuZqg7sOnIUSHvPrBdSV1uIFFRp0iduiSYWw5A2npY0M7Liy3iiZYNaqJYFa6tdpUI1K2CQCgXdv1VQLegdetRaXWzncsPwvdd9AAQ701c7kN31ijX/00CctokDhf/I36MsJQCPon2J5jkp+qQ2FUQABaNlEuM/Xtnqxk4zEq4GG16jVU5a+vAIDQ8iw84CIKArmfhrrQKXYVyCDPa19fM6YgWHwYJRrG7KJDIoXDjBFnFYgNwyQJubkOiY0I3/F57zTChfnQIJ34HeKTV8WlK18pcuv7cq9OWgvdlFsfHkHiBSgEUx5MalLSTmsq1FBrvXbxy2mYuceYTvawNrV6RnM5H3ini109frFkLVkUtrgJxQXZu5tiyYmMW6A2Muhy4N4IdRnwuTtQMR9VPG68M5Inp3WqbQDAcSl6rPQDkiJqDi06ki9ESqhxA5tKjoTcYvXmOKfgtu05RccHNUbC0oY/W0W3JARUWH5sjU3RDP9YP+KBER2jmsw2KZzk3faD6nlzbNqrwHw52DNgrw=
deploy:
  provider: npm
  skip_cleanup: true
  email: webapps.ops@ni.com
  api_key:
    secure: ZLp8K471A2sfQXSDM7zy6j6yizdAorghyAmKgKNOU6BMKUvRhE24iaj8JakBTc777SGno9B2y9cNf2Uv5/mjOLueZn9bSlO8Jj5pnPooqr9ZHEwr6kCotRf5GP5YxovkRfo0e5xBgQ8mW1EwCd+a1IQ09PQBceJu1ZZ90ThwRm1scjNwNbZZn+54j/yEZjxIx6QNnE73LaKKVnPYYl+UocONZ2TVJY4p2+mFm1jn5mH2nUz2dDe2ka+L9x79tZHT2lkpjklgl3a5KhhchXvSPAAfO7Y09HAkLyI5aYQU0fSHe6thrr8lt/tNkRoqPtWTRhdwjtI8qDtTctMYBfLqtTkAaAUPTJVMmdbCuvp8Sp3Ay88O/wlGSitLEV0z9DhnIWLxWShTCi5qJol+4flyKvb2wlk8tS+qdAkB0lz/gWktpOJlyV3WpKNjQcr0NDkvOW+Bm3mTd7W2+s2HTW1RBMjSlkR2L+I0UsHc00W0TCga+CoSaGYunluyT5HItcrEEh5C2JFX99yAXnHp6ZJWOH25YHKaOup84v3Kb1vdXT+1BpV8bWK+SPC8UYQQJMmVyazYHiHOfKcfd/ohWof/nc1ns1btrUlarBPeYvXEcChlliWtlCI0gl6hy1SQA8mTtf+0FQ6DLRfNNv1+q9LFHa/n1ZVUPL9MuDSM4G1y6ps=
  on:
    tags: true
    repo: flot/flot-plugins
